// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PINRezultati.Models;

namespace PINRezultati.Migrations
{
    [DbContext(typeof(PINRezultatiContext))]
    partial class PINRezultatiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PINRezultati.Models.Rezultati.Rezultati", b =>
                {
                    b.Property<int>("studId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ocjenaKolokvij")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ocjenaProjekt")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("studMb")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("studId");

                    b.ToTable("Rezultati");
                });
#pragma warning restore 612, 618
        }
    }
}
